### ISSUE TITLE
Add support for user to define values through environment

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#11]
Currently, all the values of the terminal interfaces are hardcoded in constants.ts
We want to load it from the environment if it is defined in the environment. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas and ask questions.

**Comment by rupeshghosh10** [comment]
hey @thtauhid, I want to work on this. Please assign it to me. Thanks
