### ISSUE TITLE
Create better dummy data

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#19]
I have put some dummy data, but it can be much much better in terms of quality and quantity. 
Feed free to improve the quality and quantity of the data. 
Try to make the data look real-ish.

**Comment by irfanfaraaz** [comment]
Can i enhance this? @thtauhid

**Comment by thtauhid** [comment]
@irfanfaraaz go ahead. 
I've assigned the issue to you.
