### ISSUE TITLE
Allow visitor to set his/her name

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#3]
Create a command such that the user is able to set his/her name. 
The name should show in place of `visitor`

**Comment by LinhNguyenLe2109** [comment]
Hi, I believe I can handle this issue

**Comment by Paulie-Aditya** [comment]
few things to add:
about command should show the name set by the user
the command.toLowerCase should be removed so that people can enter their name in capitals too

**Comment by thtauhid** [comment]
Hi @Paulie-Aditya can you create a new issue mentioning these two?

**Comment by thtauhid** [comment]
Implemented through #53
