### ISSUE TITLE
Ability to visit the project links

### ISSUE THREAD

**Issue by Y1a2s3h4** [thtauhid/terminal-portfolio#34]
- I can help you to create feature where visitors can select the project.
  - This is for hacktoberfest 2023.
   - Also we can change the font theme to something terminal based font.

**Comment by thtauhid** [comment]
Hi @Y1a2s3h4,
Please proceed to work on the following feature under the current issue- 
- Create a feature where visitors can select the project & see/visit the link of the project

Feel free to create another issue if you wish to work on the following- 
- Also we can change the font theme to something terminal-based font.

I will label both PRs `hacktober-accepted` once they are ready to be merged. 

I appreciate your interest in open source. 

Regards
THT

**Comment by Y1a2s3h4** [comment]
Yes, Thank You.
I'll Just create another issue for font theme.

**Comment by thtauhid** [comment]
You can use dummy links.
