### ISSUE TITLE
Allow adding details to any of commands

### ISSUE THREAD

**Issue by Kritika30032002** [thtauhid/terminal-portfolio#37]
- [x] #42
- [x] #38
- [x] #39
- [x] #40

**Comment by thtauhid** [comment]
Hi @Kritika30032002,

Thank you for your interest in this project. 

Feel free to add details if you want this feature to be implemented. 

If you want to implement this feature yourself, please write down 1-2 lines about what you are going to implement. 

Regards
THT

**Comment by Kritika30032002** [comment]
1. experience - command can be added
2. about answer can be made little bit more detailed.
3. contact can also provide details like LinkedIn id and GitHub along with email.
4. Skills can be described specifying languages ad tools.

**Comment by thtauhid** [comment]
Hi @Kritika30032002 

```
experience - command can be added
```
=> Can you please explain it a bit more, sounds interesting. 


```
about answer can be made little bit more detailed.
contact can also provide details like LinkedIn id and GitHub along with email.
Skills can be described specifying languages ad tools.
```
=> I'll go ahead and create separate issues for these. I'll also convert this issue into EPIC issue. I'll also assign them to you. Sounds good?

**Comment by thtauhid** [comment]
@Kritika30032002 I've created separate issues.
Please comment on the issues so that I can assign them to you. 

Thanks

**Comment by Kritika30032002** [comment]
1. experience - command can be added  ------ this command will display the work experience of the person.
2. about answer can be made little bit more detailed.  --------- about right now is just showing the name. The designation like student or professional can be added along with current position.
3. contact can also provide details like LinkedIn id and GitHub along with email.  ------- right now it only displays email to contact
4. Skills can be described specifying languages and tools.  ----------- skills like react, tailwind, redux can be specified to show proficiency in that technology.

**Comment by Kritika30032002** [comment]
> @Kritika30032002 I've created separate issues. Please comment on the issues so that I can assign them to you.
> 
> Thanks

also plz add hacktoberfest label to all

**Comment by thtauhid** [comment]
Oh. Understood. 
I'll create issue for `experience - command can be added` this one too. 
Comment on it so I can assign it to you. 

I'll add hacktoberfest label also. 

Thanks for your interest in this project. 


Regards
THT

**Comment by Kritika30032002** [comment]
Thanks for believing in my ideas.

**Comment by thtauhid** [comment]
@Kritika30032002 your ideas are awesome. Feel free to contribute more ideas. The open-source community needs people like you.

**Comment by Kritika30032002** [comment]
Thanks for your appreciation.
Will definitely contribute more ideas after completing these.

**Comment by Kritika30032002** [comment]
@thtauhid  The details to be added is of specific person or dummy data?

**Comment by thtauhid** [comment]
Dummy Data

**Comment by Kritika30032002** [comment]
Okay

**Comment by thtauhid** [comment]
@Kritika30032002 wow! 
Thanks for the huge contribution. 

Feel free to share your thoughts.

**Comment by Kritika30032002** [comment]
It was the great experience.
Happy to contribute.
