### ISSUE TITLE
about answer can be made little bit more detailed.

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#38]

**Comment by Kritika30032002** [comment]
assign this to me

**Comment by praptisharma28** [comment]
Hey @thtauhid  ,I want to work on this, could you please assign it to me? Thank you!

**Comment by thtauhid** [comment]
Hi @praptisharma28 
@Kritika30032002 is already working on this issue. Feel free to reach out to her if she wants to collaborate with you on this issue. 

You can also take a look at other issues available from https://github.com/users/thtauhid/projects/1/views/2

Thanks for your interest.
