### ISSUE TITLE
Create multiple themes

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#4]
---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas and ask questions.

**Comment by Vilayat-Ali** [comment]
I would like to take it

**Comment by Vilayat-Ali** [comment]
Lemme know what themes are we actually looking for.

**Comment by thtauhid** [comment]
Hi @Vilayat-Ali 

The main thing is, we need support for multiple themes. 
The functionalities can be as follows-
1. There will be 2/3 themes (color schemes). Feel free to experiment with colors. 
2. The visitor will be able to view existing themes when they run `themes` command
3. The visitor should be able to change the theme using a command like `settheme xyz`

Let me know if you have any questions. 

Thanks

**Comment by thtauhid** [comment]
Hi @Vilayat-Ali have you had a chance to dive into the issue yet? Need any help?

**Comment by Vilayat-Ali** [comment]
Yes. I have added 2 themes till now. Will add one more and then raise a PR

**Comment by thtauhid** [comment]
Okay

**Comment by thtauhid** [comment]
Please create a draft PR or post updates on this issue whenever you get a chance to do so.

**Comment by Vilayat-Ali** [comment]
We have 3 themes.
1. Ubuntu
2. Matrix (green and black)
3. (Still figuring out what) 
Any suggestions. I m planning to go for arch theme

**Comment by thtauhid** [comment]
Arch is a good option.

**Comment by thtauhid** [comment]
Completed #76
