### ISSUE TITLE
Replacing John Doe with user input

### ISSUE THREAD

**Issue by Paulie-Aditya** [thtauhid/terminal-portfolio#49]
It's very easy to implement, we can just ask for the username, email of the user and show that in the about and contact commands

If this issue looks okay to implement, pls do assign me the same.

**Comment by thtauhid** [comment]
Hi @Paulie-Aditya 
Thanks for your interest. 

If I understand you correctly, you are proposing to allow the visitor to set their name, email, etc. through command?
The feature to set name is already work-in-progress under #3. 
There is no need to allow the visitor to set their email in my opinion. 

Do share your thoughts.

Thanks again for your interest.

**Comment by Paulie-Aditya** [comment]
ah didn't see that it's under discussion already. The email part could be useful for the $contact command.
I was envisioning something of a personal portfolio, currently it's a static one showing only a few projects and all but if people could come in, enter a few details and have their personal portfolio in a terminal format would be a great addition imo.

**Comment by thtauhid** [comment]
That's definitely some food for thought. But for now, this is not in the scope of this project. 

I really appreciate you providing your feedback and thoughts. 
Feel free to suggest new features. 

Thanks
THT
