### ISSUE TITLE
Allow user to change theme

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#5]
---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas and ask questions.

**Comment by tylerjusfly** [comment]
when you mean change theme , do you mean something like a dark mode , and other modes?

**Comment by thtauhid** [comment]
This issue is related to #4.
Check this comment I think you'll get the idea https://github.com/thtauhid/terminal-portfolio/issues/4#issuecomment-1742735223
This issue if for implementing the 3rd point discussed in the comment.

**Comment by tylerjusfly** [comment]
okay , looks like it has been assigned.
i will be on the look out

**Comment by Vilayat-Ali** [comment]
I have completed this. Thanks

**Comment by thtauhid** [comment]
Completed in #76
