### ISSUE TITLE
Adding that clear command In available command

### ISSUE THREAD

**Issue by Dimple-Choudhary** [thtauhid/terminal-portfolio#59]
Adding clear commands in the available command  below the "contact",
`clear` <= same as this 

will you please assign me this issue under hacktoberfest'23?

**Comment by RANJEETJ06** [comment]
this is already done

plz close it #59

**Comment by thtauhid** [comment]
Hi @RANJEETJ06 
You are right. `clear` command is already in place. 
Check https://github.com/thtauhid/terminal-portfolio/issues/59#issuecomment-1742695894, we might do a bit of modification.

**Comment by RANJEETJ06** [comment]
> Hi @RANJEETJ06 You are right. `clear` command is already in place. Check [#59 (comment)](https://github.com/thtauhid/terminal-portfolio/issues/59#issuecomment-1742695894), we might do a bit of modification.

what kind of modification required

**Comment by RANJEETJ06** [comment]
do you want to display at the starting point to show that ?

**Comment by Dimple-Choudhary** [comment]
I can move the clear command to the bottom can you assign me this issue?

**Comment by thtauhid** [comment]
> Yes, I can move the clear command to the bottom can you assign me this issue?

Please create a new issue, I'll assign that to you. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by thtauhid** [comment]
> do you want to display at the starting point to show that ?

When the app starts we show the help texts. 
![image](https://github.com/thtauhid/terminal-portfolio/assets/13254850/7ef87461-43b8-4c3f-8cdb-c5f0a4cc489b)

This text is not in sync with the actual help texts which is- 
![image](https://github.com/thtauhid/terminal-portfolio/assets/13254850/76abe5ba-be12-4c8e-a464-b32e7c72ef52)

We need to make them the same. 
I hope I am able to explain. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others. 
You can

**Comment by RANJEETJ06** [comment]
> > do you want to display at the starting point to show that ?
> 
> When the app starts we show the help texts. ![image](https://user-images.githubusercontent.com/13254850/271974574-7ef87461-43b8-4c3f-8cdb-c5f0a4cc489b.png)
> 
> This text is not in sync with the actual help texts which is- ![image](https://user-images.githubusercontent.com/13254850/271974686-76abe5ba-be12-4c8e-a464-b32e7c72ef52.png)
> 
> We need to make them the same. I hope I am able to explain.
> 
> Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

got the point
