### ISSUE TITLE
Automatic Scrolling Should Be There

### ISSUE THREAD

**Issue by VivekBaldha0712** [thtauhid/terminal-portfolio#67]
I have encountered an issue on site where the automatic scrolling feature does not work as expected. When the output exceeds the visible screen area, users are required to manually scroll down to view the full result. This behavior is counterintuitive and disrupts the user experience.

**Comment by thtauhid** [comment]
Hi @VivekBaldha0712 
Thanks for the bug report. 

Marking this issue to be fixed.

**Comment by Dimas-Saputra-Me** [comment]
Can I work on this issue?

**Comment by hritikadhikari05** [comment]
Hey @thtauhid  I want to know, this issue still exists?
If yes, then can you assign this issue to me?
So, I can work on this..

**Comment by thtauhid** [comment]
Hi @hritikadhikari05 
Someone has created a PR already (though it hasn't been merged yet). 
If the PR doesn't end up being merged, I'll assign this issue to you. 


---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by hritikadhikari05** [comment]
> Hi @hritikadhikari05 Someone has created a PR already (though it hasn't been merged yet). If the PR doesn't end up being merged, I'll assign this issue to you.
> 
> Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

Sure!!
