### ISSUE TITLE
Allow user to navigate through his/her past commands through keyboard arrow keys

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#8]
Ideally, the user should be able to navigate through his/her command history using the up and down arrow keys. 
Currently, no such integration is in place. 
This needs to be implemented.

**Comment by deafwired** [comment]
I would like to do this

**Comment by Akash0420** [comment]
I would Like to be Assigned to do this

**Comment by thtauhid** [comment]
Assigning it to @deafwired  as he asked for it first. 
Feel free to take suggestions from @RANJEETJ06  in case you need any. 

@Akash0420 Sorry I am not able to assign this issue to you at this moment. There are more issues in this repo, please take a look. 

Thanks everyone for your interest.

**Comment by thtauhid** [comment]
Implemented in #47
